# USEFUL EMOJIS
'''
🧰	:toolbox:
📊	:bar_chart:
📉	:chart_decreasing:
📈	:chart_increasing:
🗒️	:spiral_notepad:
📓	:notebook:
📔	:notebook_with_decorative_cover:
✏️	:pencil:
📋	:clipboard:
⏰	:alarm_clock:
🐜	:ant:
🚛	:articulated_lorry:
⚛️	:atom_symbol:
🧠	:brain:
🎯	:bullseye:
💥	:collision:
🔢	:input_numbers:
♾️	:infinity:
🔡	:input_latin_lowercase:
💻	:laptop:
🗨️	:left_speech_bubble:
🔐	:locked_with_key:
📣	:megaphone:
📱	:mobile_phone:
💰	:money_bag:
🏢	:office_building:
🗝️	:old_key:
📂	:open_file_folder:
📄	:page_facing_up:
✏️	:pencil:
🚫	:prohibited:
🧩	:puzzle_piece:
📌	:pushpin:
🏫	:school:
🫨	:shaking_face:
🛡️	:shield:
⚔️	:交叉放置的剑:
🌳	:落叶树:
🌲	:evergreen_tree:
🪾	:leafless_tree:
🌴	:palm_tree:
🎋	:tanabata_tree:
🧬	:DNA:
☺️	:smiling_face:
😎	:smiling_face_with_sunglasses:
💖	:sparkling_heart:
✨	:sparkles:
💬	:speech_balloon:
🕷	:spider:
🕷️	:spider:
🕸️	:spider_web:
⭐	:star:
📏	:straight_ruler:
☀️	:sun:
⛅	:sun_behind_cloud:
🌄	:sunrise_over_mountains:
📆	:tear-off_calendar:
☎️	:telephone:
🌡	:thermometer:
📐	:triangular_ruler:
🏆	:trophy:
🌷	:tulip:
⬆️	:up_arrow:
⬇️	:down_arrow:
⬅️	:left_arrow:
➡️	:right_arrow:
↩️	:right_arrow_curving_left:
🪟	:window:
🛜	:wireless:
🗺	:world_map:
🔧	:wrench:
🧟	:zombie:
💤	:睡着:
✈️	:飞机:
⚗️	:蒸馏器:
🪣	:桶:
⏳	:hourglass_not_done:
‼️	:double_exclamation_mark:
⁉️	:exclamation_question_mark:
❗	:red_exclamation_mark:
🚨	:警车灯:
🛑	:停止标志:
⚠️	:警告:
'''
